### ISSUE TITLE
Error running segmeth command

### ISSUE THREAD

**Issue by simpsonbp** [adamewing/methylartist#11]
When I run segmeth, I get the following UnicodeDecodeError :

methylartist segmeth -d 3294.txt -i px551_chrm_label.bed -p 32 --excl_ambig

/home/simpsonb/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py:19: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from jupyter_client.session import utcnow as now
2022-03-09 10:30:24,883 starting methylartist with command: /home/simpsonb/anaconda3/bin/methylartist segmeth -d 3294.txt -i px551_chrm_label.bed -p 32 --excl_ambig
Traceback (most recent call last):
  File "/home/simpsonb/anaconda3/bin/methylartist", line 4, in <module>
    __import__('pkg_resources').run_script('methylartist==1.1.0', 'methylartist')
  File "/home/simpsonb/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/simpsonb/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/home/simpsonb/anaconda3/lib/python3.7/site-packages/methylartist-1.1.0-py3.7.egg/EGG-INFO/scripts/methylartist", line 4464, in <module>
  File "/home/simpsonb/anaconda3/lib/python3.7/site-packages/methylartist-1.1.0-py3.7.egg/EGG-INFO/scripts/methylartist", line 4201, in main
  File "/home/simpsonb/anaconda3/lib/python3.7/site-packages/methylartist-1.1.0-py3.7.egg/EGG-INFO/scripts/methylartist", line 1941, in segmeth
  File "/home/simpsonb/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Any ideas what the problem is?

**Comment by adamewing** [comment]
My guess is there's something unusual about `3294.txt` as the error occurs trying to read the data file. The `0x8b in position 1` message suggests it's gzipped. Is this file gzipped (if it is, it shouldn't be)? What happens if you `cat 3294.txt`?

**Comment by simpsonbp** [comment]
It was the .txt file--I had cat the .db and .bam files > .txt file. I remade the .txt with a single line for .db and .bam. Code works now. Thank you.

**Comment by adamewing** [comment]
great!
