### ISSUE TITLE
ValueError: Could not interpret input 'sample'

### ISSUE THREAD

**Issue by Fatihlrcfs** [adamewing/methylartist#15]
Hi @adamewing,

Again thank you for providing this package. I am working on 8 different samples and trying seqplot. In order to generate a .tsv file, I create a .txt file which contains 8 samples nanopolish.db and bam files.   Also, the .tsv file looks like same as what you give as an example. When ı type the " methylartist segplot -s newmegalodonano.allcombined_data_nanopolish.excl_ambig.segmeth.tsv" command, I am getting error below. Also I am ataching my file.txt and .tsv file thanks.  
2022-05-19 10:49:04,542 starting methylartist with command: /cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist segplot -s newmegalodonano.allcombined_data_nanopolish.excl_ambig.segmeth.tsv
2022-05-19 10:49:04,602 available samples: 24methylationcalls,27methylationcalls,29methylationcalls,31methylationcalls,56methylationcalls,61methylationcalls,76methylationcalls,77methylationcalls
2022-05-19 10:49:04,602 available mods: CpG
2022-05-19 10:49:04,602 sample + mod permutations: 24methylationcalls_CpG,27methylationcalls_CpG,29methylationcalls_CpG,31methylationcalls_CpG,56methylationcalls_CpG,61methylationcalls_CpG,76methylationcalls_CpG,77methylationcalls_CpG
2022-05-19 10:49:04,679 useable sites: 0
2022-05-19 10:49:04,692 plot data written to newmegalodonano.allcombined_data_nanopolish.excl_ambig.segmeth.mc10.mr1.segplot_data.csv
Traceback (most recent call last):
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist", line 4727, in <module>
    main(args)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist", line 4454, in main
    args.func(args)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist", line 2370, in segplot
    sns_plot = sns.stripplot(x='sample', y='modbase', data=plot_data, hue='group', dodge=True, jitter=True, size=pt_sz, hue_order=order, palette=args.palette)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/lib/python3.9/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/lib/python3.9/site-packages/seaborn/categorical.py", line 2807, in stripplot
    plotter = _StripPlotter(x, y, hue, data, order, hue_order,
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/lib/python3.9/site-packages/seaborn/categorical.py", line 1099, in __init__
    self.establish_variables(x, y, hue, data, orient, order, hue_order)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/lib/python3.9/site-packages/seaborn/categorical.py", line 153, in establish_variables
    raise ValueError(err)
ValueError: Could not interpret input 'sample' 
[allcombined_data_nanopolish.txt](https://github.com/adamewing/methylartist/files/8728289/allcombined_data_nanopolish.txt)
[allcombined_data_nanopolish.txt](https://github.com/adamewing/methylartist/files/8728300/allcombined_data_nanopolish.txt)

**Comment by adamewing** [comment]
Could you paste the first 10 lines or so of `newmegalodonano.allcombined_data_nanopolish.excl_ambig.segmeth.tsv`?

Also, in the `segmeth` command to generate this, unless you're looking at transposable elements or some other kind of repeat I don't recommend the `--excl_ambig` option. Note to self to remove this from the examples...

**Comment by Fatihlrcfs** [comment]
Hi @adamewing ,

thank you for quick reply. here first 10 line my tsw file
[10line.txt](https://github.com/adamewing/methylartist/files/8728394/10line.txt)

**Comment by partha434** [comment]
I have the same issue,
any option to solve this error?

**Comment by adamewing** [comment]
Sorry for the long delay on this one. It's caused by a lack of methylation calls (methylated or unmethylated) over the regions in the input to `segplot`. The most recent version (1.2.4) now includes a more helpful error message related to this.
