### ISSUE TITLE
Issue setting height ratios with methylartist locus

### ISSUE THREAD

**Issue by malonematt** [adamewing/methylartist#17]
Hi Adam,

I was having issues with methylartist locus where the height ratios is not automatically matching the rows of the grid. 
I have included the log below: 

+ DATA=dataFiles/YF_OF_data.txt
+ sortedGTF=/scratch1/malonema/heartmethyl/plotregions/resources/061021_RepeatMasker_FishTEDB_combo_w_genes_full.sorted.gtf
+ REGION=CM025017.1:43292744-43306912
+ methylartist locus -i CM025017.1:43292744-43306912 -d dataFiles/YF_OF_data.txt -g /scratch1/malonema/heartmethyl/plotregions/resources/061021_RepeatMasker_FishTEDB_combo_w_genes_full.sorted.gtf -p 16 --motif CG --svg
2022-05-31 11:32:16,934 starting methylartist with command: /home1/malonema/.conda/envs/segmethsnake/bin/methylartist locus -i CM025017.1:43292744-43306912 -d dataFiles/YF_OF_data.txt -g /scratch1/malonema/heartmethyl/plotregions/resources/061021_RepeatMasker_FishTEDB_combo_w_genes_full.sorted.gtf -p 16 --motif CG --svg
2022-05-31 11:32:17,004 found mods: m in db /scratch1/malonema/heartmethyl/methylartist_dir/YF1.db
2022-05-31 11:32:17,004 fetching reads from /scratch1/malonema/heartmethyl/meg_output/allsamples/YF1_sorted_mod_mappings.bam with mod m
2022-05-31 11:32:17,431 found mods: m in db /scratch1/malonema/heartmethyl/methylartist_dir/YF2.db
2022-05-31 11:32:17,432 fetching reads from /scratch1/malonema/heartmethyl/meg_output/allsamples/YF2_sorted_mod_mappings.bam with mod m
2022-05-31 11:32:18,119 found mods: m in db /scratch1/malonema/heartmethyl/methylartist_dir/YF3.db
2022-05-31 11:32:18,120 fetching reads from /scratch1/malonema/heartmethyl/meg_output/allsamples/YF3_sorted_mod_mappings.bam with mod m
2022-05-31 11:32:20,366 found mods: m in db /scratch1/malonema/heartmethyl/methylartist_dir/OF1.db
2022-05-31 11:32:20,366 fetching reads from /scratch1/malonema/heartmethyl/meg_output/allsamples/OF1_sorted_mod_mappings.bam with mod m
2022-05-31 11:32:20,850 found mods: m in db /scratch1/malonema/heartmethyl/methylartist_dir/OF2.db
2022-05-31 11:32:20,851 fetching reads from /scratch1/malonema/heartmethyl/meg_output/allsamples/OF2_sorted_mod_mappings.bam with mod m
2022-05-31 11:32:22,586 found mods: m in db /scratch1/malonema/heartmethyl/methylartist_dir/OF3.db
2022-05-31 11:32:22,586 fetching reads from /scratch1/malonema/heartmethyl/meg_output/allsamples/OF3_sorted_mod_mappings.bam with mod m
2022-05-31 11:32:26,058 region size: 14168
2022-05-31 11:32:26,058 mod space positions: 297
2022-05-31 11:32:26,058 auto set --modspace 1
2022-05-31 11:32:26,059 auto set --smoothwindowsize 24
Traceback (most recent call last):
  File "/home1/malonema/.conda/envs/segmethsnake/bin/methylartist", line 4794, in <module>
    main(args)
  File "/home1/malonema/.conda/envs/segmethsnake/bin/methylartist", line 4514, in main
    args.func(args)
  File "/home1/malonema/.conda/envs/segmethsnake/bin/methylartist", line 2753, in locus
    gs = gridspec.GridSpec(5,1,height_ratios=p_ratios, hspace=0)
  File "/home1/malonema/.conda/envs/segmethsnake/lib/python3.6/site-packages/matplotlib/gridspec.py", line 422, in __init__
    height_ratios=height_ratios)
  File "/home1/malonema/.conda/envs/segmethsnake/lib/python3.6/site-packages/matplotlib/gridspec.py", line 54, in __init__
    self.set_height_ratios(height_ratios)
  File "/home1/malonema/.conda/envs/segmethsnake/lib/python3.6/site-packages/matplotlib/gridspec.py", line 128, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid

**Comment by adamewing** [comment]
Hi! What is the command-line argument, are you using `-p`/`--panelratios`?

**Comment by adamewing** [comment]
Added more helpful error message in [75a87d5](https://github.com/adamewing/methylartist/commit/75a87d542647dfd0c7dc63d71d9bf6b8c97bf631)
