### ISSUE TITLE
Methylartist wgmeth - IndexError: list index out of range

### ISSUE THREAD

**Issue by jo-ong** [adamewing/methylartist#30]
Hi there, trying to get the following to work, however kept meeting this error with 2 different .fa anf .fai. can help to enlight me what is wrong?

methylartist wgmeth --bam sample.sorted.minimap2.bam --fai GRCh38.primary_assembly.genome.fa.fai --mod m --dss --motif CG --ref GRCh38.primary_assembly.genome.fa

Error:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/users/astar/gis/ongct1/miniconda3/envs/navin/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist", line 1141, in get_meth_calls_wg
    for row in parse_methbam(bam_fn, set(reads), chrom, seg_start, seg_end, meth_thresh=0.8, can_thresh=0.8, restrict_ref=args.ref, restrict_motif=args.motif):
  File "/home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist", line 668, in parse_methbam
    genome_pos = ap[len(rec.seq)-base_pos[i]-1]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist", line 4826, in <module>
    main(args)
  File "/home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist", line 4546, in main
    args.func(args)
  File "/home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist", line 4458, in wgmeth
    seg_meth_table = res.get()
  File "/home/users/astar/gis/ongct1/miniconda3/envs/navin/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

Thanks!

**Comment by navinbr** [comment]
Following this thread - @jo-ong and I hope to make 5mC DSS compatible files from our nanopore mapped BAM (with methyl tags) with the above parameters. Thank you!

**Comment by adamewing** [comment]
If you haven't already, try pulling the latest changes from the repo, run
`python setup.py install` and try again - If it's a 1bp motif ("C") I think
I ran into the same thing not long ago and pushed a fix (
424ddf654806bbd1cef4d6ac73b806c743d13884).

**Comment by navinbr** [comment]
Thanks @adamewing will give that a try. But the motif is indeed "--motif CG" and we wish to extract 5mCpG to make the DSS compatible file. So we chose "--mod m --motif CG" - is this not correct, and is this perhaps the cause of the "IndexError: list index out of range" error?

**Comment by adamewing** [comment]
I've verified that `wgmeth` in 1.2.6 works with mod .bams on my end - let me know if you are still having trouble.

**Comment by jo-ong** [comment]
[submitted_to_github_e443358.txt](https://github.com/adamewing/methylartist/files/9956970/submitted_to_github_e443358.txt)

@adamewing 
Our run still fails but seems to process a little longer before it fails, attached is the error. We aim to create a DDS output file of the 5mCpG, is the using parameters --mod m --motif CG --dds correct?
I have created the fai using samtools faidx without any error, that is the recommended way right?
The fastq files are generated from nanopore sequencing which have Ml/Mm tags, it passed through minimap2 and samtools to generate bam, index and sort. 

Do help to see what we can do to make it work. 
Thanks!

**Comment by navinbr** [comment]
For Adam - (just to edit Jo's post above, as there was a typo in the message - we indeed used the correct spelling --dss as you can see in the log file).

**Comment by jo-ong** [comment]
@adamewing I just tried on version 1.2.6 as well but same error.

**Comment by adamewing** [comment]
Thanks for the update. Yes, your command line looks good. Could you try adding `--primary_only` to the command line and let me know if anything changes? Thanks for your patience.

**Comment by jo-ong** [comment]
Below is the output, the traceback with Indexerror is not there.

2022-11-08 12:49:49,509 starting methylartist with command: /home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist wgmeth --primary_only --bam WHF196-T1.sorted.minimap2.bam --fai /scratch/users/astar/gis/ongct1/Projects/navin/ref/chm13v2.0.fa.fai --mod m --dss --motif CG --ref /scratch/users/astar/gis/ongct1/Projects/navin/ref/chm13v2.0.fa
2022-11-08 12:49:49,520 motif size 2 (CG)
2022-11-08 12:49:49,554 starting methylartist with command: /home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist wgmeth --primary_only --bam WHF195-T1.sorted.minimap2.bam --fai /scratch/users/astar/gis/ongct1/Projects/navin/ref/chm13v2.0.fa.fai --mod m --dss --motif CG --ref /scratch/users/astar/gis/ongct1/Projects/navin/ref/chm13v2.0.fa
2022-11-08 12:49:49,566 motif size 2 (CG)
2022-11-08 12:49:49,608 starting methylartist with command: /home/users/astar/gis/ongct1/miniconda3/envs/navin/bin/methylartist wgmeth --primary_only --bam WHF197-T1.sorted.minimap2.bam --fai /scratch/users/astar/gis/ongct1/Projects/navin/ref/chm13v2.0.fa.fai --mod m --dss --motif CG --ref /scratch/users/astar/gis/ongct1/Projects/navin/ref/chm13v2.0.fa
2022-11-08 12:49:49,620 motif size 2 (CG)
2022-11-08 12:49:49,705 fetching mod types from WHF196-T1.sorted.minimap2.bam, if this takes awhile MM/ML tags may be missing.
2022-11-08 12:49:49,719 found mods: h,m
2022-11-08 12:49:49,759 fetching mod types from WHF195-T1.sorted.minimap2.bam, if this takes awhile MM/ML tags may be missing.
2022-11-08 12:49:49,768 found mods: h,m
2022-11-08 12:49:49,802 fetching mod types from WHF197-T1.sorted.minimap2.bam, if this takes awhile MM/ML tags may be missing.
2022-11-08 12:49:49,816 found mods: h,m

**Comment by jo-ong** [comment]
Done with version 1.2.6, with --primary only added to command line. The traceback with Indexerror is missing but there is no output at all.

2022-11-08 12:49:49,509 starting methylartist with command: /home/miniconda3/bin/methylartist wgmeth --primary_only --bam WHF196-T1.sorted.minimap2.bam --fai /scratch/Projects/navin/ref/chm13v2.0.fa.fai --mod m --dss --motif CG --ref /scratch/Projects/navin/ref/chm13v2.0.fa
2022-11-08 12:49:49,520 motif size 2 (CG)
2022-11-08 12:49:49,554 starting methylartist with command: /home/miniconda3/bin/methylartist wgmeth --primary_only --bam WHF195-T1.sorted.minimap2.bam --fai /scratch/Projects/navin/ref/chm13v2.0.fa.fai --mod m --dss --motif CG --ref /scratch/Projects/navin/ref/chm13v2.0.fa
2022-11-08 12:49:49,566 motif size 2 (CG)
2022-11-08 12:49:49,608 starting methylartist with command: /home/miniconda3/bin/methylartist wgmeth --primary_only --bam WHF197-T1.sorted.minimap2.bam --fai /scratch/Projects/navin/ref/chm13v2.0.fa.fai --mod m --dss --motif CG --ref /scratch/Projects/navin/ref/chm13v2.0.fa
2022-11-08 12:49:49,620 motif size 2 (CG)
2022-11-08 12:49:49,705 fetching mod types from WHF196-T1.sorted.minimap2.bam, if this takes awhile MM/ML tags may be missing.
2022-11-08 12:49:49,719 found mods: h,m
2022-11-08 12:49:49,759 fetching mod types from WHF195-T1.sorted.minimap2.bam, if this takes awhile MM/ML tags may be missing.
2022-11-08 12:49:49,768 found mods: h,m
2022-11-08 12:49:49,802 fetching mod types from WHF197-T1.sorted.minimap2.bam, if this takes awhile MM/ML tags may be missing.
2022-11-08 12:49:49,816 found mods: h,m

**Comment by adamewing** [comment]
That looks OK to me - when the jobs finish running you should see a message somethine like: <timestamp> writing WHF196-T1.sorted.minimap2.m.DSS.txt. If it is taking too long you might try running on more than one process via `-p`, I usually use 32-64 cores for `wgmeth`.

**Comment by jo-ong** [comment]
Hi Adam, the job ended without any output when I posted the above. Same when I restarted the job with -p 32

**Comment by jo-ong** [comment]
I only see the "found mods" message and the job I submitted sent out completed message. However, I just went in now to confirm and I found that the last job I started with -p 32 did generated the DSS.txt files after about 50 mins. The job actually continued even when it supposed to have completed. Thanks! I see that the files contains the below, can check if that is what we should be seeing?

chr     pos     N       X
chr1    2180    1       0
chr1    2722    1       1
chr1    2729    1       0
chr1    2732    1       1
chr1    2735    1       1
chr1    2753    1       1
chr1    2758    1       0
chr1    2761    1       0
chr1    2787    1       1

**Comment by navinbr** [comment]
Hi Jo. Yes this is a good output file. That’s great to hear it works with -p 32!

**Comment by adamewing** [comment]
While that's good to hear I'd double check that the output doesn't seem truncated (e.g. doesn't end in the middle of a chromosome) given the absence of the final status message (should start with "writing") - is this on a cluster environment where it might be terminated for using too much memory?

**Comment by navinbr** [comment]
Hi Adam, I'm comparing the DSS output with modbam2bed output to see if there's any inadvertent truncation and will get back to you on that.

But in the meantime, we need your help for one last part. We're also attempting wgmeth DSS output with the --phased option using a haplotagged-BAM. (haplotagging was done using whatshap haplotag as in https://labs.epi2me.io/gm24385-5mc-remora/). The default tags are specified as "1" and "2" as you can see in the IGV snapshot of an imprinted locus (SNRPN).

We ran the following: methylartist wgmeth --primary_only -p 32 --bam ${BAMFILE} --fai ${INDEX} --mod m --dss --motif CG --ref ${REF} --phased
but got this error - "Error: no calls for phase 0: is this data phased?"

Perhaps this is because it's searching for phase 0, when the phases are tagged as 1 and 2? 
Any help appreciated, thanks Adam!
<img width="974" alt="Screenshot 2022-11-11 at 4 09 09 PM" src="https://user-images.githubusercontent.com/13088810/201295049-079c6e55-c4c6-4f3f-b129-804294b52eab.png">

**Comment by adamewing** [comment]
Good theory, I really should change the error message, but in this case it's because it's an index into a python array (because of this return: https://github.com/adamewing/methylartist/blob/95b803b621b955ef96a03e112e932416d4befa50/methylartist#L1453) so index 0 is reads with phase "HP:1" and index 1 is "HP:2" - `wgmeth` would actually throw an assertion error if anything other than phases 1 or 2 is encountered (https://github.com/adamewing/methylartist/blob/95b803b621b955ef96a03e112e932416d4befa50/methylartist#L1419). Are you able to plot the SNRPN region via `methylartist locus` with `--phased`?

**Comment by navinbr** [comment]
Hi Adam. In summary methylartist locus with --phased works nicely as attached.
Jo and I ran: methylartist locus --bam BAMFILE -m m --motif CG --ref REF --phased -i chr15:24953240-24958602

However, methylartist wgmeth to make phased DSS output files threw up the error:
methylartist wgmeth --primary_only -p 32 --bam BAMFILE --fai INDEX --mod m --dss --motif CG --ref REF --phased
and got this error - "Error: no calls for phase 0: is this data phased?"

We inspected the bam and can indeed see HP:I:1 and HP:i:2 for reads that could be phased, and of course alongside no HP tags on reads that could not be phased.

Let me know your thoughts on this. Thank you!
![WHF195-T1 hp chr15_24953240_24958602 m phased ms1 smw20 locus meth](https://user-images.githubusercontent.com/13088810/201854554-944c2e52-ff50-4648-9a5d-54310f60a7d2.png)
