### ISSUE TITLE
Using a large BAI or CSI Index with Composite Function

### ISSUE THREAD

**Issue by pgrady1322** [adamewing/methylartist#39]
Hello! I have a very large set of chromosomes (749Mb is the largest) I'm working on which BAI indexes are too small for, and this seems to be throwing and error with methylartist composite specifically:

`2023-02-09 15:51:39,395 starting methylartist with command: /anaconda3/envs/methylartist/bin/methylartist composite -s HAL1-3_ME.BED31.bed -r assembly.fasta -t HAL1-3_ME_Consensus.fasta -b Methyl.bam --motif CG
2023-02-09 15:51:39,864 fetching mod types from Methyl.bam, if this takes awhile MM/ML tags may be missing.
2023-02-09 15:51:39,892 found mods: m
2023-02-09 15:51:39,899 found mod names: m
2023-02-09 15:51:39,899 using the one available mod: m
2023-02-09 15:51:39,899 composite output filename: Methyl.HAL1-3_ME.BED31.composite.png
2023-02-09 15:51:39,957 profiling Methyl.bam: chr1:10701-12136:+:m phase: None
Traceback (most recent call last):
  File "/anaconda3/envs/methylartist/bin/methylartist", line 5313, in <module>
    main(args)
  File "/anaconda3/envs/methylartist/bin/methylartist", line 5010, in main
    args.func(args)
  File "/anaconda3/envs/methylartist/bin/methylartist", line 4655, in composite
    elif c[4] in ('-', '+'):
         ~^^^
IndexError: list index out of range`

I've managed to successfully run methyartist segplot with the same bamtools BAI indexes without any issues. Is there a way around this where I can use a CSI index or the bamtools forced BAI index? Thank you!

**Comment by adamewing** [comment]
Hey, I bet this is a bug. Looking at the error message what I think is going on here is that the file `HAL1-3_ME.BED31.bed` doesn't have enough columns in it. the `-s` option to `composite` _should_ be fine with a BED3+1 but it appears that I'm trying to check the 5th column (c[4]). Will fix but as a quick workaround, try adding something as an additional column (i.e. make it BED3+2) - doesn't really matter what. Let me know if that works.

If that doesn't solve it I'll test with a .csi index but they _should_ be supported as I'm just using pysam to do the .bam parsing.

**Comment by pgrady1322** [comment]
Thanks so much for the quick response! Unfortunately there still seems to be a hangup - I tried moving around the strand information to column 5, adding more information, and copying the strand to multiple columns. I get the same error each time, but not the index error:

`strand (+/-) not found in cols 4 or 5 of HAL1-3_ME.BED32.bed`

Up until this point, it gives the exact same output as above prior to the "Traceback (most recent call)....".

**Comment by adamewing** [comment]
[848c7be](https://github.com/adamewing/methylartist/commit/848c7be1cf42d3c02ba3b5ac378c303fbe2e2727) should fix the index oob error. Not sure about the further issue here but assume it was a record in the .bed file not complying with chrom, start, end, strand, Please re-open if still an issue you're contending with.
