### ISSUE TITLE
question with installation

### ISSUE THREAD

**Issue by rl4940** [adamewing/methylartist#44]

**Comment by rl4940** [comment]
I install the methylartist from pip install, and gives me error messages.
code for installations:
```
 mamba create -n methylartist
```
```
 conda activate methylartist
```
```
pip install methylartist
```
And the errors like this:
configure: error: libbzip2 development files not found
    
    The CRAM format may use bzip2 compression, which is implemented in HTSlib
    by using compression routines from libbzip2 <http://www.bzip.org/>.
    
    Building HTSlib requires libbzip2 development files to be installed on the
    build machine; you may need to ensure a package such as libbz2-dev (on Debian
    or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
    is installed.
    
    Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    Makefile:131: htscodecs.mk: No such file or directory
    config.mk:2: *** Resolve configure error first.  Stop.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qQj5Ga/pysam/setup.py", line 381, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-build-qQj5Ga/pysam/setup.py", line 79, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qQj5Ga/pysam/
You are using pip version 9.0.1, however version 23.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I am not sure what is going on.
Thanks!

**Comment by keenhl** [comment]
Have you tried to install with mamba instead of pip ?

mamba install methylartist
