### ISSUE TITLE
Segmeth error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by sonalhenson** [adamewing/methylartist#50]
Really useful tool and am looking forward to using it. However, I can't get beyond the first step. I am trying to run segmeth but I get the below error. Would greatly appreciate any leads to resolve it. Thank you.

**methyartist version**: 1.2.3 (installed using conda)
**Command:** methylartist segmeth -b ../sample.haplotagged.bam --ref genome.fa --motif CG -i ../genome.bed -p 32
**Std out:**

2023-06-19 15:10:17,156 found mod names: m,h                                                                                                               
2023-06-19 15:10:17,156 segmeth output filename: genome.sample.haplotagged.segmeth.tsv                                         
[W::hts_idx_load3] The index file is older than the data file: ../sample.haplotagged.bam.bai                                 
[W::hts_idx_load3] The index file is older than the data file: ../sample.haplotagged.bam.bai       
2023-06-19 15:10:17,640 warning: collision between mods, this is a bug! report me!
2023-06-19 15:10:17,640 warning: collision between mods, this is a bug! report me!

**Error message:**
multiprocessing.pool.RemoteTraceback:  
"""
Traceback (most recent call last):
  File "/XXX/XXX/miniconda3/envs/methylartist/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/XXX/XXX/miniconda3/envs/methylartist/bin/methylartist", line 729, in get_segmeth_calls
    for row in parse_methbam(bam_fn, reads, chrom, seg_start, seg_end, meth_thresh=0.8, can_thresh=0.8, restrict_ref=args.ref, restrict_motif=args.motif):
  File "/XXX/XXX/miniconda3/envs/methylartist/bin/methylartist", line 676, in parse_methbam
    genome_pos = ap[base_pos[i]]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "XXX/XXX/miniconda3/envs/methylartist/bin/methylartist", line 4826, in <module>
    main(args)
  File "/XXX/XXX/miniconda3/envs/methylartist/bin/methylartist", line 4546, in main
    args.func(args)
  File "/XXX/XXX/miniconda3/envs/methylartist/bin/methylartist", line 2179, in segmeth
    meth_result, seg = res.get()
  File "/XXX/XXX/miniconda3/envs/methylartist/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
IndexError: list index out of range

**Comment by adamewing** [comment]
Hi, hope we can get it working for you. Let's upgrade from 1.2.3, that's quite old, the conda build for methylartist broke quite awhile back and I don't have the bandwidth to troubleshoot nor was it obvious how to remove something from bioconda. In your methylartist env could you run:

```
git clone https://github.com/adamewing/methylartist.git
cd methylartist
pip install -e $PWD
```

Try the same command with the updated version and let me know how you go.

**Comment by sonalhenson** [comment]
Thanks for the quick reply Adam. The latest version works.
