### ISSUE TITLE
NameError: name 'b' is not defined

### ISSUE THREAD

**Issue by itslittman** [adamewing/methylartist#51]
When I run:

methylartist locus -b sample1.bam,sample2.bam,sample3.bam -i chr9:130711881-130889675 -g hg38.sorted.gtf.gz --genes ABL1 --ref hg38.analysis.fa --motif 5mCpG

I get the error:

Traceback (most recent call last):
  File "/Users/.../miniforge3/bin/methylartist", line 5522, in <module>
    main(args)
  File "/Users/.../miniforge3/bin/methylartist", line 5210, in main
    args.func(args)
  File "/Users/.../miniforge3/bin/methylartist", line 2791, in locus
    assert iupac(args.motif)
  File "/Users/.../miniforge3/bin/methylartist", line 527, in iupac
    sys.exit('base %s not an IUPAC base, please modify --motif' % b)
NameError: name 'b' is not defined

I'm probably missing something obvious but I can't figure this out.

Noah

**Comment by itslittman** [comment]
But it works with CG...does this depend on the contents of the MM,ML tags or something?

**Comment by adamewing** [comment]
--motif is meant to be a sequence (e.g. "CG") rather than an identifier like "CpG" or "5mCpG". The error message also had a typo in it which I've just fixed so thanks for that!

--Adam

**Comment by itslittman** [comment]
Thanks!
