### ISSUE TITLE
mm10 genome

### ISSUE THREAD

**Issue by srkndgn** [adamewing/methylartist#52]
Dear @adamewing, 
Thank you for this great tool. I would like to use methylartist  for mm10 genome. I am new in coding and  I am trying to use Mus_musculus.GRCm38.dna.primary_assembly.fa.gz but it gives error ; error when opening file `GRCm38.p6.genome.fa.gz`
Can you please guide me what to do in this case.
Best,
Serkan

**Comment by srkndgn** [comment]
Thanks for your help. I am really new in coding. Here is my command line;

 methylartist locus -b E4.merged.sup.mod.sort.bam -i chr18:36778332-37297840 --samplepalette cubehelix -g Mus_musculus.GRCm38.91.chr.sorted.gtf.gz --labelgenes --ref GRCm38.p6.fasta.fa.gz
2023-06-30 15:16:52,539 starting methylartist with command: /exports/humgen/Serkan/anaconda3/envs/methylartist/bin/methylartist locus -b E4.merged.sup.mod.sort.bam -i chr18:36778332-37297840 --samplepalette cubehelix -g Mus_musculus.GRCm38.91.chr.sorted.gtf.gz --labelgenes --ref GRCm38.p6.fasta.fa.gz
2023-06-30 15:16:52,539 mod motif size (--motifsize) = 2 (ensure this is correct for your data)
2023-06-30 15:16:52,539 --ref and --motif are required when using --bams

**Comment by adamewing** [comment]
Sorry for the delay, try adding `--motif CG` onto te end of the command line.

**Comment by adamewing** [comment]
The other thing I might suggest is using an uncompressed reference genome that has been indexed via `samtools faidx`.

**Comment by srkndgn** [comment]
Thank you again for the answer and sorry for the simple questions which take your time . I have the following files below in my working directory and I ran the code again with --motif CG. But I have again some error. Do you have any other suggestion.

Files in my working directory:
E4.merged.sup.mod.sort.bam
E4.merged.sup.mod.sort.bam.bai
GRCm38.p6.genome.fa
Mus_musculus.GRCm38.91.chr.sorted.gtf.gz
Mus_musculus.GRCm38.91.chr.sorted.gtf.gz.tbi


(methylartist) $ methylartist locus -b E4.merged.sup.mod.sort.bam -i chr18:36778332-37297840 --samplepalette cubehelix -g Mus_musculus.GRCm38.91.chr.sorted.gtf.gz --labelgenes --ref GRCm38.p6.genome.fa --motif CG

2023-07-03 08:18:13,972 starting methylartist with command: 
methylartist locus -b E4.merged.sup.mod.sort.bam -i chr18:36778332-37297840 --samplepalette cubehelix -g Mus_musculus.GRCm38.91.chr.sorted.gtf.gz --labelgenes --ref GRCm38.p6.genome.fa --motif CG
2023-07-03 08:18:13,972 mod motif size (--motifsize) = 2 (ensure this is correct for your data)
[W::hts_idx_load3] The index file is older than the data file: E4.merged.sup.mod.sort.bam.bai
2023-07-03 08:18:13,997 fetching mod types from E4.merged.sup.mod.sort.bam, if this takes awhile MM/ML tags may be missing.
2023-07-03 08:18:14,001 found mods: m
2023-07-03 08:18:14,005 found mods: m in bam E4.merged.sup.mod.sort.bam
2023-07-03 08:18:14,006 fetching reads from E4.merged.sup.mod.sort.bam with mod m
[W::hts_idx_load3] The index file is older than the data file: E4.merged.sup.mod.sort.bam.bai
[W::hts_idx_load3] The index file is older than the data file: E4.merged.sup.mod.sort.bam.bai
2023-07-03 08:18:15,808 region size: 519508
2023-07-03 08:18:15,808 mod space positions: 5105
2023-07-03 08:18:15,808 auto set --modspace 4
2023-07-03 08:18:15,808 auto set --smoothwindowsize 104
2023-07-03 08:18:15,828 building genes plot...
Traceback (most recent call last):
  File "/anaconda3/envs/methylartist/bin/methylartist", line 5522, in <module>
    main(args)
  File "/anaconda3/envs/methylartist/bin/methylartist", line 5210, in main
    args.func(args)
  File "/anaconda3/envs/methylartist/bin/methylartist", line 3215, in locus
    genes = build_genes(gtf, chrom, elt_start, elt_end)
  File "/Serkan/anaconda3/envs/methylartist/bin/methylartist", line 1656, in build_genes
    for line in gtf.fetch(chrom, start, end):
  File "pysam/libctabix.pyx", line 507, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region 'chr18:36778333-37297840'

**Comment by srkndgn** [comment]
Hi Adam, 
It worked with the genecode annotation but it is not working with other annotations; where is my mistake; do you have any suggestion for simple mm10 annotation
methylartist locus -b E4.merged.sup.mod.sort.bam -i chr18:36778332-37297840 --samplepalette cubehelix -g gencode.vM22.annotation.sorted.gtf.gz --labelgenes --ref GRCm38.p6.genome.fa --motif CG


2023-07-03 08:33:42,496 starting methylartist with command: /exports/humgen/Serkan/anaconda3/envs/methylartist/bin/methylart                                    ist locus -b E4.merged.sup.mod.sort.bam -i chr18:36778332-37297840 --samplepalette cubehelix -g gencode.vM22.annotation.sort                                    ed.gtf.gz --labelgenes --ref GRCm38.p6.genome.fa --motif CG
2023-07-03 08:33:42,497 mod motif size (--motifsize) = 2 (ensure this is correct for your data)
[W::hts_idx_load3] The index file is older than the data file: E4.merged.sup.mod.sort.bam.bai
2023-07-03 08:33:42,521 fetching mod types from E4.merged.sup.mod.sort.bam, if this takes awhile MM/ML tags may be missing.
2023-07-03 08:33:42,525 found mods: m
2023-07-03 08:33:42,530 found mods: m in bam E4.merged.sup.mod.sort.bam
2023-07-03 08:33:42,530 fetching reads from E4.merged.sup.mod.sort.bam with mod m
[W::hts_idx_load3] The index file is older than the data file: E4.merged.sup.mod.sort.bam.bai
[W::hts_idx_load3] The index file is older than the data file: E4.merged.sup.mod.sort.bam.bai
2023-07-03 08:33:44,372 region size: 519508
2023-07-03 08:33:44,373 mod space positions: 5105
2023-07-03 08:33:44,373 auto set --modspace 4
2023-07-03 08:33:44,373 auto set --smoothwindowsize 104
2023-07-03 08:33:44,395 building genes plot...
2023-07-03 08:33:44,435 gene in region: Hars
2023-07-03 08:33:44,472 gene in region: Hars2
2023-07-03 08:33:44,475 gene in region: Zmat2
2023-07-03 08:33:44,476 gene in region: Vaultrc5
2023-07-03 08:33:44,476 gene in region: Gm23424
2023-07-03 08:33:44,477 gene in region: Gm6756
2023-07-03 08:33:44,478 gene in region: Pcdha1
2023-07-03 08:33:44,479 gene in region: Gm37751
2023-07-03 08:33:44,480 gene in region: Pcdha2
2023-07-03 08:33:44,481 gene in region: Pcdha3
2023-07-03 08:33:44,481 gene in region: Pcdha4
2023-07-03 08:33:44,483 gene in region: Gm38225
2023-07-03 08:33:44,483 gene in region: Gm42416
2023-07-03 08:33:44,484 gene in region: Pcdha5
2023-07-03 08:33:44,485 gene in region: Gm37753
2023-07-03 08:33:44,486 gene in region: Pcdha6
2023-07-03 08:33:44,487 gene in region: Gm37013
2023-07-03 08:33:44,488 gene in region: Pcdha7
2023-07-03 08:33:44,489 gene in region: Gm37388
2023-07-03 08:33:44,490 gene in region: Gm36858
2023-07-03 08:33:44,491 gene in region: Pcdha8
2023-07-03 08:33:44,492 gene in region: Pcdha9
2023-07-03 08:33:44,493 gene in region: Pcdha11
2023-07-03 08:33:44,494 gene in region: Gm10545
2023-07-03 08:33:44,494 gene in region: Pcdha11
2023-07-03 08:33:44,496 gene in region: Gm18150
2023-07-03 08:33:44,497 gene in region: Pcdha12
2023-07-03 08:33:44,498 gene in region: Gm19035
2023-07-03 08:33:44,499 gene in region: Pcdhac1
2023-07-03 08:33:44,500 gene in region: Pcdhac2
2023-07-03 08:33:44,501 gene in region: Gm10544
2023-07-03 08:33:44,502 gene in region: Gm38097
2023-07-03 08:33:44,503 gene in region: Pcdhb1
2023-07-03 08:33:44,503 gene in region: Pcdhb2
2023-07-03 08:33:44,586 building read alignment plot...
[W::hts_idx_load3] The index file is older than the data file: E4.merged.sup.mod.sort.bam.bai
2023-07-03 08:33:58,651 building mod-space plot...
2023-07-03 08:33:58,931 building llr plot...
2023-07-03 08:35:02,506 building meth frac plot...
2023-07-03 08:35:29,043 chr18:36778332-37297840 (m), sample E4.merged.sup.mod.sort.m fraction masked: 0.063
2023-07-03 08:35:40,992 plot saved to E4.merged.sup.mod.sort.chr18_36778332_37297840.m.ms4.smw104.locus.meth.png

**Comment by adamewing** [comment]
My guess is that one gtf file uses chromosome names that start with "chr" and the other doesn't? It can work either way but all inputs (.bam file, genome, annotation, and command line) need to agree with respect to this.

**Comment by srkndgn** [comment]
Thank you for your support, Adam.
