### ISSUE TITLE
Issues with Bam files from Dorado with segmeth

### ISSUE THREAD

**Issue by Jared-Tomei** [adamewing/methylartist#55]
I merged the bam files from the modified 5mc and 5hmC from Dorado with samtools merge, I index and sorted it with samtools as well.
when I try to run methylartist segmeth with this bam file as my -b I get this as an error.
Traceback (most recent call last):
  File "/usr/local/bin/methylartist", line 5522, in <module>
    main(args)
  File "/usr/local/bin/methylartist", line 5210, in main
    args.func(args)
  File "/usr/local/bin/methylartist", line 2381, in segmeth
    mod_names = mods_methbam(bam)
  File "/usr/local/bin/methylartist", line 686, in mods_methbam
    bam = pysam.AlignmentFile(bam_fn)
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 1000, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

Is there something I need to do to the bam files from dorado before merging and indexing them?

**Comment by adamewing** [comment]
Apologies for the delay. If this is still relevant, can you check that there are reads in the .bam (`samtools view`)?

In general .bam files from dorado seem to work fine in methylartist without any further processing.
