### ISSUE TITLE
issue with split_on_adapter output

### ISSUE THREAD

**Issue by itslittman** [adamewing/methylartist#56]
Hi,
My modbams were working great as input for methylartist until I ran them through ONT's duplex_tools split_on_adapter module to split up concatemers in my data. I think the additional manipulation of the input files made methylartist not know what columns to find some of the information in or something. Is there an easy fix for this or do I have to use my input as-is without splitting on adapter?

noah

**Comment by adamewing** [comment]
I haven't tried this myself so not sure - can you paste the actual error message in a reply?

**Comment by itslittman** [comment]
It says 

Traceback (most recent call last):
  File "/Users/me/miniforge3/bin/methylartist", line 5522, in <module>
    main(args)
  File "/Users/me/miniforge3/bin/methylartist", line 5210, in main
    args.func(args)
  File "/Users/me/miniforge3/bin/methylartist", line 2934, in locus
    reads[bamname] = get_meth_locus(args, bam, meth_dbs, mod, methbam=methbam, restrict_motif=args.motif, restrict_ref=args.ref)
  File "/Users/me/miniforge3/bin/methylartist", line 1078, in get_meth_locus
    for row in parse_methbam(bam, reads, chrom, elt_start, elt_end, motifsize=args.motifsize, meth_thresh=0.8, can_thresh=0.8, restrict_motif=restrict_motif, restrict_ref=restrict_ref, primary_only=args.primary_only):
  File "/Users/me/miniforge3/bin/methylartist", line 880, in parse_methbam
    genome_pos = ap[len(rec.seq)-base_pos[i]-1]
IndexError: list index out of range

for the split file and produces no error when I run the unsplit file for the same sample

noah
