### ISSUE TITLE
Error when running segmeth   Value error: invalid contig

### ISSUE THREAD

**Issue by malonematt** [adamewing/methylartist#6]
Hi Adam, 

Sorry to keep bothering you. I ran into this error when running methylartist segmeth. I have included below the error traceback. This seems similar to an issue I was having when running tldr, which also kicked up an error when I ran it that to me looked similar as it also had to do with the chromosome CM025008.1. If you get a chance to look at this, if you could also let me know if it is related to the issue in tldr that would be fantastic (I have an open issue for this on tldr's page as well). Let me know if you can figure this out as I'd really love to run this tldr on this run as well. And let me know if any further information would be helpful. Thanks again for this great software, I have some high hopes for the information it could deliver on this organism. 

nohup: ignoring input and appending output to 'nohup.out'
+ data=/project/bbenayou_34/malone/nanopore/methylartist/scripts/data.txt
+ inputFile=/project/bbenayou_34/malone/nanopore/methylartist/0610FishTEDBGTFtutorial.bed
+ methylartist segmeth -d /project/bbenayou_34/malone/nanopore/methylartist/scripts/data.txt -i /project/bbenayou_34/malone/nanopore/methylartist/0610FishTEDBGTFtutorial.bed -p 32 --excl_ambig
2022-01-13 10:57:19,614 starting methylartist with command: /home1/malonema/.local/bin/methylartist segmeth -d /project/bbenayou_34/malone/nanopore/methylartist/scripts/data.txt -i /project/bbenayou_34/malone/nanopore/methylartist/0610FishTEDBGTFtutorial.bed -p 32 --excl_ambig
2022-01-13 10:57:19,623 found mod names: m
2022-01-13 10:57:19,623 segmeth output filename: 0610FishTEDBGTFtutorial.data.excl_ambig.segmeth.tsv
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.9.2-uvcroioc4witkp6qf7mbebof5ix4wlb6/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home1/malonema/.local/bin/methylartist", line 512, in get_segmeth_calls
    reads = exclude_ambiguous_reads(bam_fn, chrom, seg_start, seg_end, min_mapq=int(args.min_mapq), spanning_only=args.spanning_only) 
File "/home1/malonema/.local/bin/methylartist", line 368, in exclude_ambiguous_reads
    for read in bam.fetch(chrom, start, end):
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `"CM025008.1"`
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/malonema/.local/bin/methylartist", line 3770, in <module>
    main(args)
  File "/home1/malonema/.local/bin/methylartist", line 3547, in main
    args.func(args)
  File "/home1/malonema/.local/bin/methylartist", line 1609, in segmeth
    meth_result, seg = res.get()
  File "/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.9.2-uvcroioc4witkp6qf7mbebof5ix4wlb6/lib/python3.9/multiprocessing/pool.py", line 771, in get 
    raise self._value
ValueError: invalid contig `"CM025008.1"`

**Comment by adamewing** [comment]
If you're referencing issue 23 on tldr, I don't think that's related. This one just looks like the bed file you're using might contain contigs not present in at least one of the .bam files. What happens if you try `samtools view your.bam CM025008.1 | head`?
