### ISSUE TITLE
segmeth error . 

### ISSUE THREAD

**Issue by senukobla** [adamewing/methylartist#66]
I am trying to run segmeth but I am getting the error below.

(methylartist) apewoksu@x86_64-apple-darwin13 cdiffshins % methylartist segmeth -d B9t016formethy.txt  -i  BC9to16blow5   -o testmth -p 32 
2023-12-20 14:43:57,381 starting methylartist with command: /Users/apewoksu/miniconda3/envs/methylartist/bin/methylartist segmeth -d B9t016formethy.txt -i BC9to16blow5 -o testmth -p 32
Traceback (most recent call last):
  File "/Users/apewoksu/miniconda3/envs/methylartist/bin/methylartist", line 5522, in <module>
    main(args)
  File "/Users/apewoksu/miniconda3/envs/methylartist/bin/methylartist", line 5210, in main
    args.func(args)
  File "/Users/apewoksu/miniconda3/envs/methylartist/bin/methylartist", line 2345, in segmeth
    bam, meth = line.strip().split()[:2]
ValueError: not enough values to unpack (expected 2, got 1)

Any thoughts on how to resolve ?

**Comment by senukobla** [comment]
figured it out - NVM
