### ISSUE TITLE
Still doesn't work with output of ONT duplex tools split_on_adapter

### ISSUE THREAD

**Issue by itslittman** [adamewing/methylartist#67]
Methylartist still doesn't work on BAMs processed with _duplex_tools split_on_adapter_. After splitting, I map, then _sed -E 's/ [0-9]+->[0-9]+$//g' split.mapped.sam > split.mapped.fixed.sam_ . Then I can convert to BAM, sort, and index/view in IGV/etc. but I still get an error with methylartist. I opened an case back in September but it's still a problem. It was easier to have a split copy and an unsplit copy of each BAM when I used MinION, but PromethION runs result in 150-200GB BAMs...

**Comment by adamewing** [comment]
Could you paste the full error if you still have it (sorry for the delay in getting back), I want to see if there is any context around the KeyError that might be helpful (e.g. which line(s) it's coming from in the script)

**Comment by Grigory-Kornienko** [comment]
Hi, 
I get the same error. I will paste it here in case you still want to have a look:  

`2024-05-06 12:02:45,297 motif size 2 (CG)
2024-05-06 12:02:45,534 fetching mod types from cell_lines_sorted.bam, if this takes awhile MM/ML tags may be missing.
2024-05-06 12:02:45,535 found mods: h,m
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/trinity/home/gnkornienko/miniconda3/envs/orri/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/trinity/home/gnkornienko/miniconda3/envs/orri/bin/methylartist", line 1400, in get_meth_calls_wg
    seg_reads[index] = Read(index, cg_seg_start, stat, methstate, modname, phase=reads[index])
                                                                                 ~~~~~^^^^^^^
KeyError: 'c840ea5c-9eaa-4bc2-83ff-7579571a556e'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/trinity/home/gnkornienko/miniconda3/envs/orri/bin/methylartist", line 5755, in <module>
    main()
  File "/trinity/home/gnkornienko/miniconda3/envs/orri/bin/methylartist", line 5427, in main
    args.func(args)
  File "/trinity/home/gnkornienko/miniconda3/envs/orri/bin/methylartist", line 5327, in wgmeth
    seg_meth_table = res.get()
                     ^^^^^^^^^
  File "/trinity/home/gnkornienko/miniconda3/envs/orri/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
KeyError: 'c840ea5c-9eaa-4bc2-83ff-7579571a556e'`

Hopefully this will help! 
Which version of methylartist can I use to avoid this error? 

Best regards,
Grigory Kornienko

**Comment by Alan-Xu1** [comment]
Hi, could you share which version did you end up using?
