### ISSUE TITLE
segmeth - not enoug values to unpack

### ISSUE THREAD

**Issue by 0Bernhard** [adamewing/methylartist#7]
Hello 
I am new to methylartist and i encountered a problem when runing segmeth. When i try to run it i get this error (see below). Can someone help me to correct this?  What file is the error refering to? 

Thank you very much!

methylartist segmeth -d mod_mappings_minimap2.txt -i J1074_new.bed -p 32 --excl_ambig
2022-01-26 09:49:51,279 starting methylartist with command: /home/holly/miniconda3/envs/modbam2bed/bin/methylartist segmeth -d mod_mappings_minimap2.txt -i J1074_new.bed -p 32 --excl_ambig
2022-01-26 09:49:51,279 found mod names: m
2022-01-26 09:49:51,279 segmeth output filename: J1074_new.mod_mappings_minimap2.excl_ambig.segmeth.tsv
Traceback (most recent call last):
  File "/home/holly/miniconda3/envs/modbam2bed/bin/methylartist", line 4, in <module>
    __import__('pkg_resources').run_script('methylartist==1.0.7', 'methylartist')
  File "/home/holly/miniconda3/envs/modbam2bed/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/holly/miniconda3/envs/modbam2bed/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/holly/miniconda3/envs/modbam2bed/lib/python3.10/site-packages/methylartist-1.0.7-py3.10.egg/EGG-INFO/scripts/methylartist", line 4428, in <module>
  File "/home/holly/miniconda3/envs/modbam2bed/lib/python3.10/site-packages/methylartist-1.0.7-py3.10.egg/EGG-INFO/scripts/methylartist", line 4171, in main
  File "/home/holly/miniconda3/envs/modbam2bed/lib/python3.10/site-packages/methylartist-1.0.7-py3.10.egg/EGG-INFO/scripts/methylartist", line 2016, in segmeth
ValueError: not enough values to unpack (expected 3, got 1)

**Comment by 0Bernhard** [comment]
sorry my bad i had a csv file as bed file
