### ISSUE TITLE
wgmeth: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by J35P312** [adamewing/methylartist#71]
Hello!
And thanks for creating such a nice tool! I have been trying to run wgmeth on a phased bam file, however it crashes with this error message:

2024-01-31 21:10:01,458 writing 2023-34375-05/2023-34375-05.happlotagged.bam.happlotagged.m.methyl.bed
Traceback (most recent call last):
  File "/usr/local/bin/methylartist", line 5592, in <module>
    main()
  File "/usr/local/bin/methylartist", line 5272, in main
    args.func(args)
  File "/usr/local/bin/methylartist", line 5222, in wgmeth
    meth_table[phase]['name']   = '.'.join(args.methdb.split('.')[:-1])
AttributeError: 'NoneType' object has no attribute 'split'

I think the issue is "args.methdb" which I guess is none since the input is bam? This is the command:

/usr/local/bin/methylartist wgmeth -b 2023-34375-05/2023-34375-05.happlotagged.bam -r //home/proj/development/rare-disease/ONT/analysis/poorpipe/references/grch37_homo_sapiens_-d5-.fasta -f //home/proj/development/rare-disease/ONT/analysis/poorpipe/references/grch37_homo_sapiens_-d5-.fasta.fai --motif CG --mod m --primary_only -p 16 -q 0 --phased -o 2023-34375-05/2023-34375-05.happlotagged.bam.happlotagged.m.methyl.bed

Thanks!
best regards
Jesper

**Comment by adamewing** [comment]
Hi Jesper,

Could you tell me which version of methylartist you're using? I ask as I think I remember fixing this (could be mistaken).

--Adam

**Comment by J35P312** [comment]
Hello!
And thanks for a quick reply! Im running methylartist 1.2.10

**Comment by leenput** [comment]
Hi,

Thanks for this great tool!

I’m also trying to run wgmeth on a phased BAM file with a similar command and am encountering the same AttributeError in methylartist version 1.3.1. Do you have any advice or a possible workaround?

Thanks so much!
