### ISSUE TITLE
`locus` cannot find csi-index for gtf, but my file is out off range for tbi

### ISSUE THREAD

**Issue by skranz0** [adamewing/methylartist#85]
When indexing with tabix I get
```bash
[E::hts_idx_check_range] Region 537025265..537026246 cannot be stored in a tbi index. Try using a csi index
tbx_index_build failed: projectedGenes__Triticum_aestivum_Julius_v1.0.sorted.gtf.gz
```
So I added the `-C` flag to get a `foo.csi` file. However with this I only get 
```bash
Traceback (most recent call last):
  File "/home/anfny/.conda/envs/deepmod2/bin/methylartist", line 5755, in <module>
    main()
  File "/home/anfny/.conda/envs/deepmod2/bin/methylartist", line 5427, in main
    args.func(args)
  File "/home/anfny/.conda/envs/deepmod2/bin/methylartist", line 3382, in locus
    gtf = pysam.Tabixfile(args.gtf)
  File "pysam/libctabix.pyx", line 349, in pysam.libctabix.TabixFile.__cinit__
  File "pysam/libctabix.pyx", line 381, in pysam.libctabix.TabixFile._open
OSError: index `/home/anfny/masterarbeit/projectedGenes__Triticum_aestivum_Julius_v1.0.sorted.gtf.gz.tbi` not found
```
from methylartist.

Can I explicitly tell the tool to look for the csi?

**Comment by cmdcolin** [comment]
tried adding a PR in #87 to try to help this

**Comment by skranz0** [comment]
Thank you so much @cmdcolin !
Now I just need to find out why I still get an empty line in the plot... it says
```bash
2024-08-13 10:42:27,782 no transcript for gene: TraesJUL5B01G429800
```
So it did find the annotation (gene ID is the one I was expecting) but something is apparently still missing. Though this is probably an issue on my side and not with the tool, right?

**Comment by cmdcolin** [comment]
i can't say for sure but i would manually look at the gtf file and find TraesJUL5B01G429800 and see if there are transcript children features for it...

**Comment by cmdcolin** [comment]
this is another random thing i thought of but do the bam files not also need csi indexes?

**Comment by skranz0** [comment]
Yes the bam files were csi indexed from the beginning. That was never an issue though

**Comment by skranz0** [comment]
> i can't say for sure but i would manually look at the gtf file and find TraesJUL5B01G429800 and see if there are transcript children features for it...

I can't say I'm a super-expert but the file looks correct to me. There is the gene and children pointing to it.
```
chr5B	PGSBv2.0	gene	588454460	588466808	1429.472	-	.	gene_id "TraesJUL5B01G429800"; ID "TraesJUL5B01G429800";
chr5B	PGSBv2.0	mRNA	588454460	588466808	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1"; Parent "TraesJUL5B01G429800";
chr5B	PGSBv2.0	exon	588454460	588454568	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_8"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	exon	588454736	588454848	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_7"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	exon	588454939	588454980	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_6"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	exon	588455136	588455177	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_5"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	exon	588455373	588455472	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_4"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	exon	588455564	588455628	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_3"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	exon	588456874	588456952	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_2"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	exon	588466624	588466808	.	-	.	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "TraesJUL5B01G429800.1_exon_1"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588454460	588454568	.	-	1	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-317995"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588454736	588454848	.	-	0	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-317996"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588454939	588454980	.	-	0	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-317997"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588455136	588455177	.	-	0	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-317998"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588455373	588455472	.	-	1	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-317999"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588455564	588455628	.	-	0	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-318000"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588456874	588456952	.	-	1	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-318001"; Parent "TraesJUL5B01G429800.1";
chr5B	PGSBv2.0	CDS	588466624	588466808	.	-	0	gene_id "TraesJUL5B01G429800"; transcript_id "TraesJUL5B01G429800.1"; ID "agat-cds-318002"; Parent "TraesJUL5B01G429800.1";
```
It was originally a gff, though. I converted it with [AGAT](https://github.com/NBISweden/AGAT). I know there are multiple versions of gff and not all tools are consistent about it. Does methylartist require a specific format?

**Comment by skranz0** [comment]
After converting using gffread it worked, finally. Thanks for solving my issue! I would recommend adding more detailed instructions to the documentation
![Uploading safari_V1W0_new.chr5B_588452460_588468808.m.cohort.ms1.smw28.locus.meth.png…]()

**Comment by skranz0** [comment]
![safari_V1W0_new chr5B_588452460_588468808 m cohort ms1 smw28 locus meth](https://github.com/user-attachments/assets/45389a4a-7e57-4b56-86db-f54d875655c5)
