### ISSUE TITLE
Issue with updating to version 1.3.1

### ISSUE THREAD

**Issue by ntillquist** [adamewing/methylartist#97]
Hi,

I have successfully run wgmeth using version 1.2.3 in the past but came across an error recently in trying to run it:

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
File "/home/FCAM/ntillquist/miniconda3/envs/MethylArtist/bin/methylartist", line 4826, in <module>
main(args)
File "/home/FCAM/ntillquist/miniconda3/envs/MethylArtist/bin/methylartist", line 4546, in main
args. func (args)
File "/home/FCAM/ntillquist/miniconda3/envs/MethylArtist/bin/methylartist", line 4458, in wgmeth
seg_meth_table = res.get()
File "/home/FCAM/ntillquist/miniconda3/envs/MethylArtist/lib/python3.10/multiprocessing/pool.py", line 774, in get
raise self ._ value
ValueError: start out of range (-1)
2024-11-04 12:40:07,770 starting methylartist with command: /home/FCAM/ntillquist/miniconda3/envs/MethylArtist/bin/methylartist wgmeth -- bam /core/labs/Oneill/ntillquist/Sheep/Liver/01_rawdata/mappedreads/5.mm2_mapped.bam -- fai /core/labs/Oneill/ntillquist/Sheep/Liver/genome/GCF_016772045.2_ARS-UI_Ramb_v3.0_genomic.fna.fai -- m
od m -- procs 16 -- ref /core/labs/Oneill/ntillquist/Sheep/Liver/genome/GCF_016772045.2_ARS-UI_Ramb_v3.0_genomic.fna -- dss -- motif CG
multiprocessing.pool. RemoteTraceback:

Traceback (most recent call last):
File "/home/FCAM/ntillquist/miniconda3/envs/MethylArtist/lib/python3.10/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, ** kwds))
File "/home/FCAM/ntillquist/miniconda3/envs/MethylArtist/bin/methylartist", line 1141, in get_meth_calls_wg
for row in parse_methbam(bam_fn, set(reads), chrom, seg_start, seg_end, meth_thresh=0.8, can_thresh=0.8, restrict_ref=args.ref, restrict_motif=args.motif):
File "/home/FCAM/ntillquist/miniconda3/envs/MethylArtist/bin/methylartist", line 695, in parse_methbam
ref_motif = restrict_ref.fetch(rec.reference_name, genome_pos, genome_pos+2)
File "pysam/libcfaidx.pyx", line 290, in pysam. libcfaidx. FastaFile. fetch
File "pysam/libcutils.pyx", line 282, in pysam. libcutils.parse_region
ValueError: start out of range (-1)
```

I thought maybe it was because the version was older so I tried to update to the newest version using conda install and ran into this issue with the conda install:

```
(methylartist1.3.1) bash-4.2$ which methylartist
/home/FCAM/ntillquist/miniforge3/envs/methylartist1.3.1/bin/methylartist
(methylartist1.3.1) bash-4.2$ methylartist -v
Traceback (most recent call last):
  File "/home/FCAM/ntillquist/miniforge3/envs/methylartist1.3.1/bin/methylartist", line 29, in <module>
    import seaborn as sns
  File "/home/FCAM/ntillquist/miniforge3/envs/methylartist1.3.1/lib/python3.12/site-packages/seaborn/__init__.py", line 9, in <module>
    from .matrix import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/FCAM/ntillquist/miniforge3/envs/methylartist1.3.1/lib/python3.12/site-packages/seaborn/matrix.py", line 12, in <module>
    from . import cm
  File "/home/FCAM/ntillquist/miniforge3/envs/methylartist1.3.1/lib/python3.12/site-packages/seaborn/cm.py", line 1582, in <module>
    mpl_cm.register_cmap(_name, _cmap)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'
```

I would appreciate any advice for getting this solved

**Comment by adamewing** [comment]
Do you have any luck with `pip install methylartist` instead of conda?

**Comment by ntillquist** [comment]
Hi,

I did not, the pip install had an error for pysam and then when I tried pysam it had the same error again.

I got a version of 1.2.7 to work from a coworkers previous install but it looks like from other threads (Issue #81) that to get the m and h mods to run at the same time for wgmeth that the troubles have been fixed in 1.3.1 - is that correct?

Nicole

____________________________
Nicole Tillquist, Ph.D.
She|Her|Hers
Postdoctoral Research Associate
Department of Animal Science
University of Connecticut

________________________________

**Comment by adamewing** [comment]
Both mods at the same time would be `-m m,h` or more likely just omit `-m` as by default it'll use all available mods and the most commonly used dorado modified base model is 5mCG_5hmCG.

1.2.7 _should_ have the fix for the original issue you're reporting, can you verify that you're running 1.2.7 via `methylartist -v`?

**Comment by ntillquist** [comment]
Hi,

yes - the version is 1.2.7

will the flag -m m,h generate a .txt with the chr, N, X for the 5mCG and another column with the X for 5hmCG? When I ran it before it only would show the "m" in the file name and nothing would generate for the "h".

Nicole
____________________________
Nicole Tillquist, Ph.D.
She|Her|Hers
Postdoctoral Research Associate
Department of Animal Science
University of Connecticut

________________________________

**Comment by ntillquist** [comment]
Sorry for the double reply - I tested this in version 1.2.7 with both mods listed and it will not run both together. Has this been fixed in 1.3.1? Or is doing m and then omit m the only option? And assume that the omit m is the h?

2024-11-06 13:27:55,270 starting methylartist with command: /home/FCAM/ntillquist/miniforge3/envs/methylartist3/bin/methylartist wgmeth --bam /core/labs/Oneill/ntillquist/Sheep/Liver/01_rawdata/mappedreads/10.mm2_mapped.bam --fai /core/labs/Oneill/ntillquist/Sheep/Liver/genome/GCF_016772045.2_ARS-UI_Ramb_v3.0_genomic.fna.fai --mod m,h --procs 16 --ref /core/labs/Oneill/ntillquist/Sheep/Liver/genome/GCF_016772045.2_ARS-UI_Ramb_v3.0_genomic.fna --dss --motif CG --primary_only --outfile /core/labs/Oneill/ntillquist/Sheep/Liver/01_rawdata/methylartist_h_m_1.2.7
2024-11-06 13:27:55,329 motif size 2 (CG)
2024-11-06 13:27:55,408 fetching mod types from /core/labs/Oneill/ntillquist/Sheep/Liver/01_rawdata/mappedreads/10.mm2_mapped.bam, if this takes awhile MM/ML tags may be missing.
2024-11-06 13:27:55,414 found mods: m,h
2024-11-06 13:27:55,421 mod m,h not in known mods for db: h,m


____________________________
Nicole Tillquist, Ph.D.
She|Her|Hers
Postdoctoral Research Associate
Department of Animal Science
University of Connecticut

________________________________

**Comment by adamewing** [comment]
Ah my bad I didn't catch you were running `wgmeth` - in that case my recommendation would be run each mod independently (`-m m` and then `-m h`) sorry for the confusion. You can't omit `-m` with `wgmeth`.
