### ISSUE TITLE
Problem running run_tests.sh

### ISSUE THREAD

**Issue by IanCodes** [adamewing/methylartist#99]
Hello,

I noticed while running run_tests.sh with version 1.3.1 that there is a command with carriage returns and dead path:
```
echo -e "\nas above, with --show_transcripts, --smoothed_csv, and --exonheight ...\n"
methylartist with command: /home/taewing/miniconda3/bin/methylartist locus -b data/MCF7_ATCC.modification_tags.bam,data/MCF7_ECACC.mo
dification_tags.bam -i chr19:56172382-56187168 --samplepalette cubehelix -g data/Homo_sapiens.GRCh38.97.chr.sorted.gtf.gz --labelgenes --ref data/Homo_sapiens_assembl
y38.fasta.gz --motif CG --show_transcripts --smoothed_csv test.csv --exonheight 0.6 --panelratios 2,5,1,3,3

```
I corrected it to the following and it worked:
```
echo -e "\nas above, with --show_transcripts, --smoothed_csv, and --exonheight ...\n"
time methylartist locus -b data/MCF7_ATCC.modification_tags.bam,data/MCF7_ECACC.mo
dification_tags.bam -i chr19:56172382-56187168 --samplepalette cubehelix -g data/Homo_sapiens.GRCh38.97.chr.sorted.gtf.gz --labelgenes --ref data/Homo_sapiens_assembl
y38.fasta.gz --motif CG --show_transcripts --smoothed_csv test.csv --exonheight 0.6 --panelratios 2,5,1,3,3

```

Later on in run_tests.sh there appears to be a file missing 'test_colours.txt', resulting in the following error:
```
2024-12-05 10:21:23,455 starting methylartist with command: /mnt/fls01-home01/mqbssid3/.conda/envs/methylartist131/bin/methylartist locus -b test_colours.txt -i chr19:56172382-56187168 -g data/Homo_sapiens.GRCh38.97.chr.sorted.gtf.gz --labelgenes --ref data/Homo_sapiens_assembly38.fasta.gz --motif CG
2024-12-05 10:21:23,483 mod motif size (--motifsize) = 2 (ensure this is correct for your data)
[E::hts_open_format] Failed to open file "test_colours.txt" : No such file or directory
2024-12-05 10:21:23,484 assuming test_colours.txt contains a list of .bams
Traceback (most recent call last):
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/methylartist131/bin/methylartist", line 5903, in <module>
    main()
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/methylartist131/bin/methylartist", line 5567, in main
    args.func(args)
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/methylartist131/bin/methylartist", line 3008, in locus
    with open(args.bams) as bam_list:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test_colours.txt'
```

**Comment by adamewing** [comment]
fixed in methylartist-tests repo, thanks!
